class Logged_Exception(Exception):
    pass